### PR TITLE
test MIPS

### PR DESCRIPTION
**Pull request by japaric**
cc @tbu- one more platform to support!

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6f23756 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6f23756 with merge 6f23756...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194051645)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5d881f5 with merge 5d881f5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194062567)
State: approved= try=True

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #64) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
Let's try this again ...

@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit bc931f6 with merge bc931f6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/195654856)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e9fabe7 with merge e9fabe7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/195661936)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0754a4c with merge 0754a4c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/195665979)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 61fc606) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
I hope that #95 fixed this...

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 861a045 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 861a045 with merge 861a045...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198243502)
Approved by: japaric
Pushing 861a0457fef1869d7b9ac60ea94e951612b84fe3 to master...

**Comment by japaric** [comment]
Yay! Finally.

**Pull request merged**
