### PR TITLE
Port net stuff to the new `libc` module`

### PR DESCRIPTION
**Pull request by tbu-**
Also add the OS-specific extensions `os::unix::ext::{net, io}` relating
to net.

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 4545903 with merge 4545903...

**Comment by tbu-** [comment]
Remaining diffs:

`diff -ur ../rust/src/libstd/net/ src/net/`:
```diff
diff -ur ../rust/src/libstd/net/addr.rs src/net/addr.rs
--- ../rust/src/libstd/net/addr.rs
+++ src/net/addr.rs
@@ -12,10 +12,13 @@
 use hash;
 use io;
 use mem;
-use net::{lookup_host, ntoh, hton, IpAddr, Ipv4Addr, Ipv6Addr};
+use net::{ntoh, hton, IpAddr, Ipv4Addr, Ipv6Addr};
+#[cfg(issue = "22")]
+use net::lookup_host;
 use option;
 use sys::net::netc as c;
 use sys_common::{FromInner, AsInner, IntoInner};
+#[cfg(issue = "22")]
 use vec;
 use iter;
 use slice;
@@ -467,6 +470,7 @@
     }
 }
 
+#[cfg(issue = "22")]
 fn resolve_socket_addr(s: &str, p: u16) -> io::Result<vec::IntoIter<SocketAddr>> {
     let ips = lookup_host(s)?;
     let v: Vec<_> = ips.map(|mut a| { a.set_port(p); a }).collect();
@@ -474,6 +478,7 @@
 }
 
 #[stable(feature = "rust1", since = "1.0.0")]
+#[cfg(issue = "22")]
 impl<'a> ToSocketAddrs for (&'a str, u16) {
     type Iter = vec::IntoIter<SocketAddr>;
     fn to_socket_addrs(&self) -> io::Result<vec::IntoIter<SocketAddr>> {
@@ -495,6 +500,7 @@
 
 // accepts strings like 'localhost:12345'
 #[stable(feature = "rust1", since = "1.0.0")]
+#[cfg(issue = "22")]
 impl ToSocketAddrs for str {
     type Iter = vec::IntoIter<SocketAddr>;
     fn to_socket_addrs(&self) -> io::Result<vec::IntoIter<SocketAddr>> {
diff -ur ../rust/src/libstd/net/mod.rs src/net/mod.rs
--- ../rust/src/libstd/net/mod.rs
+++ src/net/mod.rs
@@ -13,6 +13,7 @@
 #![stable(feature = "rust1", since = "1.0.0")]
 
 use io::{self, Error, ErrorKind};
+#[cfg(issue = "22")]
 use sys_common::net as net_imp;
 
 #[stable(feature = "rust1", since = "1.0.0")]
@@ -94,12 +95,14 @@
                                               iterator and returning socket \
                                               addresses",
            issue = "27705")]
+#[cfg(issue = "22")]
 pub struct LookupHost(net_imp::LookupHost);
 
 #[unstable(feature = "lookup_host", reason = "unsure about the returned \
                                               iterator and returning socket \
                                               addresses",
            issue = "27705")]
+#[cfg(issue = "22")]
 impl Iterator for LookupHost {
     type Item = SocketAddr;
     fn next(&mut self) -> Option<SocketAddr> { self.0.next() }
@@ -131,6 +134,7 @@
                                               iterator and returning socket \
                                               addresses",
            issue = "27705")]
+#[cfg(issue = "22")]
 pub fn lookup_host(host: &str) -> io::Result<LookupHost> {
     net_imp::lookup_host(host).map(LookupHost)
 }
```

`diff -u ../rust/src/libstd/sys_common/net.rs src/sys_common/net.rs`
```diff
--- ../rust/src/libstd/sys_common/net.rs
+++ src/sys_common/net.rs
@@ -9,14 +9,18 @@
 // except according to those terms.
 
 use cmp;
+#[cfg(issue = "22")]
 use ffi::CString;
 use fmt;
 use io::{self, Error, ErrorKind};
 use libc::{c_int, c_void};
 use mem;
 use net::{SocketAddr, Shutdown, Ipv4Addr, Ipv6Addr};
+#[cfg(issue = "22")]
 use ptr;
-use sys::net::{cvt, cvt_r, cvt_gai, Socket, init, wrlen_t};
+use sys::net::{cvt, cvt_r, Socket, init, wrlen_t};
+#[cfg(issue = "22")]
+use sys::net::cvt_gai;
 use sys::net::netc as c;
 use sys_common::{AsInner, FromInner, IntoInner};
 use time::Duration;
@@ -126,11 +130,13 @@
 // get_host_addresses
 ////////////////////////////////////////////////////////////////////////////////
 
+#[cfg(issue = "22")]
 pub struct LookupHost {
     original: *mut c::addrinfo,
     cur: *mut c::addrinfo,
 }
 
+#[cfg(issue = "22")]
 impl Iterator for LookupHost {
     type Item = SocketAddr;
     fn next(&mut self) -> Option<SocketAddr> {
@@ -152,15 +158,19 @@
     }
 }
 
+#[cfg(issue = "22")]
 unsafe impl Sync for LookupHost {}
+#[cfg(issue = "22")]
 unsafe impl Send for LookupHost {}
 
+#[cfg(issue = "22")]
 impl Drop for LookupHost {
     fn drop(&mut self) {
         unsafe { c::freeaddrinfo(self.original) }
     }
 }
 
+#[cfg(issue = "22")]
 pub fn lookup_host(host: &str) -> io::Result<LookupHost> {
     init();
 
```

`diff -u ../rust/src/libstd/sys/unix/net.rs src/sys/linux/net.rs`:
```diff
--- ../rust/src/libstd/sys/unix/net.rs
+++ src/sys/linux/net.rs
@@ -8,10 +8,14 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+#[cfg(issue = "22")]
 use ffi::CStr;
 use io;
-use libc::{self, c_int, size_t, sockaddr, socklen_t, EAI_SYSTEM};
+use libc::{self, c_int, size_t, sockaddr, socklen_t};
+#[cfg(issue = "22")]
+use libc::EAI_SYSTEM;
 use net::{SocketAddr, Shutdown};
+#[cfg(issue = "22")]
 use str;
 use sys::fd::FileDesc;
 use sys_common::{AsInner, FromInner, IntoInner};
@@ -19,7 +23,9 @@
 use time::Duration;
 
 pub use sys::{cvt, cvt_r};
-pub extern crate libc as netc;
+pub mod netc {
+    pub use libc::*;
+}
 
 pub type wrlen_t = size_t;
 
@@ -45,6 +51,7 @@
 
 pub fn init() {}
 
+#[cfg(issue = "22")]
 pub fn cvt_gai(err: c_int) -> io::Result<()> {
     if err == 0 {
         return Ok(())
@@ -127,20 +134,13 @@
         // atomically set the CLOEXEC flag is to use the `accept4` syscall on
         // Linux. This was added in 2.6.28, however, and because we support
         // 2.6.18 we must detect this support dynamically.
-        if cfg!(target_os = "linux") {
-            weak! {
-                fn accept4(c_int, *mut sockaddr, *mut socklen_t, c_int) -> c_int
-            }
-            if let Some(accept) = accept4.get() {
-                let res = cvt_r(|| unsafe {
-                    accept(self.0.raw(), storage, len, SOCK_CLOEXEC)
-                });
-                match res {
-                    Ok(fd) => return Ok(Socket(FileDesc::new(fd))),
-                    Err(ref e) if e.raw_os_error() == Some(libc::ENOSYS) => {}
-                    Err(e) => return Err(e),
-                }
-            }
+        let res = cvt_r(|| unsafe {
+            libc::accept4(self.0.raw(), storage, len, SOCK_CLOEXEC)
+        });
+        match res {
+            Ok(fd) => return Ok(Socket(FileDesc::new(fd as i32))),
+            Err(ref e) if e.raw_os_error() == Some(libc::ENOSYS) => {}
+            Err(e) => return Err(e),
         }
 
         let fd = cvt_r(|| unsafe {
@@ -231,7 +231,7 @@
 
     pub fn set_nonblocking(&self, nonblocking: bool) -> io::Result<()> {
         let mut nonblocking = nonblocking as libc::c_int;
-        cvt(unsafe { libc::ioctl(*self.as_inner(), libc::FIONBIO, &mut nonblocking) }).map(|_| ())
+        cvt(unsafe { libc::ioctl(*self.as_inner(), libc::FIONBIO, &mut nonblocking as *mut _ as libc::c_ulong) }).map(|_| ())
     }
 
     pub fn take_error(&self) -> io::Result<Option<io::Error>> {
```

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198964809)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-.

**Pull request merged**
