### PR TITLE
Upgrade to Rust 1.15.0

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 06454ad with merge 06454ad...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198287482)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-. I hope this wasn't too hard!

**Comment by tbu-** [comment]
No, it was surprisingly simple, thanks to the `// Rust 1.14.0` annotations.

**Pull request merged**
