### PR TITLE
Add `fs::readlink`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Can't test locally:
```
$ cross run --target x86_64-unknown-linux-gnu --example stat --release
    Updating git repository `https://github.com/rust-lang-nursery/compiler-builtins`
    Updating git repository `https://github.com/japaric/ralloc`
    Updating git repository `https://github.com/japaric/syscall.rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling std v0.1.0 (file:///project)
error: language item required, but not found: `eh_personality`

error: aborting due to previous error

error: Could not compile `std`.

To learn more, run the command again with --verbose.
```

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 4d7cf44 with merge 4d7cf44...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194096872)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1d706ed with merge 1d706ed...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194107479)
State: approved= try=True

**Comment by tbu-** [comment]
Can be merged.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bd19d21 has been approved by `japaric`

**Comment by japaric** [comment]
Merging manually since `try`passed.

**Pull request merged**
