### PR TITLE
update the README and enable LTO for the release profile

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 61fc606 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 61fc606 with merge 61fc606...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/196357135)
Approved by: japaric
Pushing 61fc6061cc3938528f0ed82ea2314c3386076fcc to master...

**Pull request merged**
