### PR TITLE
switch to a stable release of sc

### PR DESCRIPTION
**Pull request by japaric**
also switch to upstream version of rallec

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f93e194 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f93e194 with merge 1dd6d59...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198230031)
Approved by: japaric
Pushing 1dd6d596c2e57512259e85eee6ef06aafd7f52f7 to master...

**Pull request merged**
