### PR TITLE
Copy the `io` module from Rust 1.15.0

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
We had an unused `src/io/stdio.rs` before.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0e05eaf with merge f97ba39...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/199158456)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-.

**Pull request merged**
