### PR TITLE
Upgrade net-related stuff to Rust 1.15.0

### PR DESCRIPTION
**Pull request by tbu-**
Based off #104, because that pull made it feasible. :) Just look at the second commit.

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 9065d2e with merge 9065d2e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198970415)
State: approved= try=True

**Comment by japaric** [comment]
👍

**Pull request merged**
