### PR TITLE
Start a `libc` module, port `src/sys/linux/fd.rs` to it

### PR DESCRIPTION
**Pull request by tbu-**
CC #89

### CODE REVIEW

**Comment by tbu-** [comment]
Remaining diff:
```diff
$ diff -u ../rust/src/libstd/sys/unix/fd.rs src/sys/linux/fd.rs 
--- ../rust/src/libstd/sys/unix/fd.rs
+++ src/sys/linux/fd.rs
@@ -125,7 +125,7 @@
               target_os = "haiku"))]
     pub fn set_cloexec(&self) -> io::Result<()> {
         unsafe {
-            let previous = cvt(libc::fcntl(self.fd, libc::F_GETFD))?;
+            let previous = cvt(libc::fcntl(self.fd, libc::F_GETFD, 0))?;
             cvt(libc::fcntl(self.fd, libc::F_SETFD, previous | libc::FD_CLOEXEC))?;
             Ok(())
         }
@@ -133,7 +133,7 @@
 
     pub fn set_nonblocking(&self, nonblocking: bool) -> io::Result<()> {
         unsafe {
-            let previous = cvt(libc::fcntl(self.fd, libc::F_GETFL))?;
+            let previous = cvt(libc::fcntl(self.fd, libc::F_GETFL, 0))?;
             let new = if nonblocking {
                 previous | libc::O_NONBLOCK
             } else {
```

I couldn't figure out how you can do varargs in Rust.

**Comment by tbu-** [comment]
The idea behind this is
1) to make it easier to port Rust mainline changes to steed and
2) make a potential steed integration into Rust mainline easier.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit b488965 with merge b488965...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198309731)
State: approved= try=True

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #98) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
> Remaining diff:

Nice!

> I couldn't figure out how you can do varargs in Rust.

You can't. IIRC, you can only bind to varargs functions that come from C. You could use a macro that accepts two or more patterns with different number of arguments. Maybe implementing `Fn` more than once on an empty struct would work too. But, it seems OK to leave it like this for now.

r=me after a rebase

@homunkulus delegate=tbu-

**Comment by homunkulus** [comment]
:v: @tbu- can now approve this pull request

**Comment by tbu-** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cc4f298 has been approved by `tbu-`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cc4f298 with merge cc4f298...

**Comment by tbu-** [comment]
Implementing `Fn` more than once gives strange compiler errors. :/ Too bad, I liked that idea.

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198336092)
Approved by: tbu-
Pushing cc4f2985eaf79842813dd6b43cf783d99908c758 to master...

**Pull request merged**
