### PR TITLE
gate on running steed's test suite

### PR DESCRIPTION
**Pull request by japaric**
some unit tests currently don't compile. See #115

On x86_64, I see

```
test result: ok. 174 passed; 0 failed; 18 ignored; 0 measured
```

cc @tbu-

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d2ace31 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d2ace31 with merge d2ace31...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/205353523)
Approved by: japaric
Pushing d2ace31de3ff96492b67f5ff464076b8da205b6b to master...

**Pull request merged**
