### PR TITLE
add the target-c-int-width field to the target specifications

### PR DESCRIPTION
**Pull request by japaric**
this is a new mandatory field in the target specification

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8126023 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8126023c944c9590c6334f8c070243695c81bc18 with merge 552600a3fdd13157d0a9e6a48c4892a64dbe36b8...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8bb2e86 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8bb2e868a3062782b6142286a99c25838597d24a with merge 290622547b73138c2dc1a299c309f796d682faec...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 25b81b0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 25b81b0813894aa38af252b4a4d2a7e23ec30518 with merge 5e25608ca2b196ef9d167401c7468d381964fdd6...

**Comment by japaric** [comment]
@homunkulus r

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a41cea0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a41cea0efbbf46812b81ba85c9cf5e2537fe780d with merge 6db0703236751928fd303c9f96a3434fb313b29e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/290231807?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b4a3cd5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b4a3cd51faa836daca7dd0558f1be2e5d36206d2 with merge b43eceea35d0a7d1a429be2d84d101b129421a0b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/290238410?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aacba3a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aacba3abadd41f3ee87ef59b4613dfe601f4d78c with merge 23882a1c408b922c132e9d00f0a61c4c9002c2d8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/290250421?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 23882a1c408b922c132e9d00f0a61c4c9002c2d8 to master...

**Pull request merged**
