### PR TITLE
Implement `File::set_len`

### PR DESCRIPTION
**Pull request by tbu-**
CC #18

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e713709 with merge e713709...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193565434)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit ba80a67 with merge ba80a67...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193566795)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit eb4b891 with merge eb4b891...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193571887)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-!

@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit eb4b891 has been approved by `japaric`

**Comment by homunkulus** [comment]
:zap: Test exempted: pull fully rebased and already tested.

**Pull request merged**
