### PR TITLE
bump qemu version to v0.2.9

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2fcc0de has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2fcc0de with merge 2fcc0de...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/224690119)
Approved by: japaric
Pushing 2fcc0dec2ceddf6cd3bedb5162ba619b8214d64c to master...

**Pull request merged**
