### PR TITLE
Complete the `fs` module

### LINKED ISSUE #21: implement std::fs (copy, create_dir, etc.)
This is going to require a bunch of syscall wrappers and declaring Linux structs like statvfs, etc.

### PR DESCRIPTION
**Pull request by tbu-**
Implement the missing `fs::canonicalize` function and add a bunch of platform-specific extension traits `os::unix::fs::*`.

Fixes #21.

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3ce04fd with merge 3ce04fd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/195721247)
State: approved= try=True

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 8c97108 with merge 8c97108...

**Comment by japaric** [comment]
@homunkulus r+

(let's hope homu works...)

Thanks, @tbu-

**Comment by homunkulus** [comment]
:pushpin: Commit f6ad289 has been approved by `japaric`

**Comment by japaric** [comment]
(sigh) merging manually since try passed

**Pull request merged**
