### PR TITLE
ci: don't run the `format` example twice

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2dc7dd7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2dc7dd7 with merge 8c69842...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198233088)
Approved by: japaric
Pushing 8c6984239ac9b0acc1135f7dc2a5dfde87c113b9 to master...

**Pull request merged**
