### PR TITLE
Add `path`

### LINKED ISSUE #2: implement std::path (Path, PathBuf)
This should mostly involve copy pasting the code from rust-lang/rust

### PR DESCRIPTION
**Pull request by tbu-**
Copy-paste the implementation from Rust 1.14.0.

Add shims in `fs` to support the new module as-is.

Fix #2.

### CODE REVIEW

**Comment by tbu-** [comment]
I added the `sys_common` module as the same as `sys`, so `src/sys/linux/os_str.rs` can be copied as-is from the Rust source tree.

**Comment by japaric** [comment]
@homunkulus r+

Thanks, @tbu-!

**Comment by homunkulus** [comment]
:pushpin: Commit 9f46424 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9f46424 with merge 9f46424...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192818930)
Approved by: japaric
Pushing 9f464246333baac09434d7d3ea1c813aff2a1748 to master...

**Comment by japaric** [comment]
huh? @homunkulus y u no merge?

**Pull request merged**
