### PR TITLE
fix the cache

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+ p=1

**Comment by homunkulus** [comment]
:pushpin: Commit 0920c9c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0920c9c with merge 0920c9c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194025900)
Approved by: japaric
Pushing 0920c9cff9eeabdb3d7ca2316fbe7385ce457ac6 to master...

**Pull request merged**
