### PR TITLE
fix O_LARGEFILE

### PR DESCRIPTION
**Pull request by japaric**
the value is architecture dependent

cc @tbu-

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 74e76b3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 74e76b3 with merge 74e76b3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198241392)
Approved by: japaric
Pushing 74e76b3e65438d4c608bb6099cc2ec65f52f0355 to master...

**Pull request merged**
