### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by tbu-**
Includes code from #147. Needs nightly `std` code instead of stable because stable code doesn't compile....

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit cd124a5 with merge cd124a5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/230266929?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-!

**Pull request merged**
