### PR TITLE
implement std::macro and std::rt

### PR DESCRIPTION
**Pull request by japaric**
leave out the start lang item cc #14
and the real panic! implementation cc #12

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d6fe130 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d6fe130 with merge d6fe130...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192003310)
Approved by: japaric
Pushing d6fe130308afc3f0862cc3f394f73b29a44bd127 to master...

**Pull request merged**
