### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by aleksander**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @aleksander.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 590b7d2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 590b7d2 with merge 590b7d2...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/222820055)

**Comment by tbu-** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 590b7d2 with merge 225905c...

**Comment by japaric** [comment]
> ld.lld: error: /rust/lib/rustlib/src/rust/src/liballoc/heap.rs:74: undefined symbol '__rust_allocate_zeroed'

I thought this was already fixed?

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 225905c has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 261fa9e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 261fa9e with merge 182ef95...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/224686720)

**Comment by tbu-** [comment]
Network failure?

**Comment by japaric** [comment]
URL changed and we are not telling curl to follow redirects. Should be fixed in #142.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.
- There's another pull request that is currently being tested, blocking this pull request: #140

**Comment by homunkulus** [comment]
:pushpin: Commit 261fa9e has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 261fa9e with merge 6ba428a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/224694877)
Approved by: japaric
Pushing 6ba428a5950a19f9653e747e742e56df4b21432b to master...

**Pull request merged**
