### PR TITLE
Add `File::try_clone`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Based off #70 because I also need `fcntl` here.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 7d8b430 with merge 7d8b430...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194192841)

**Comment by tbu-** [comment]
Fails in `ralloc`, looks like #73.

**Comment by japaric** [comment]
> Fails in ralloc, looks like #73.

:-(. Does it work in release mode?

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 9ab148c) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by tbu-** [comment]
@japaric Yes, it works in release mode.

**Comment by japaric** [comment]
This assertion is actually a debug assertion so disabling debug-assertions in dev mode would probably "fix" this (make the tests pass) but I'm unsure about doing that as it may let other bugs slip in.

**Comment by tbu-** [comment]
We could do it until the ralloc crate is fixed.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit d442442 with merge d442442...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194406812)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d442442 has been approved by `japaric`

**Comment by japaric** [comment]
(sigh, homu)

Merging manually.

**Pull request merged**
