### PR TITLE
Add `FileExt::{read_at, write_at}` implementation

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Just because it was so easy. :)

**Comment by japaric** [comment]
Could you add preadwrite to the list of examples we test in ci/script.sh?

Other than, r=me

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8e04729 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8e04729 with merge 8e04729...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193221244)

**Comment by tbu-** [comment]
Might this have to do with the Architecture Calling Conventions section of [man 2 syscall](http://man7.org/linux/man-pages/man2/syscall.2.html#NOTES)? Does the syscall crate handle that?.. x86 isn't mentioned as a potentially affected platform though.

**Comment by japaric** [comment]
> Might this have to do with the Architecture Calling Conventions section of man 2 syscall? 

The `syscall!` macro takes of that but note that each argument of that macro is passed through a register so it's limited to a 32-bit value on 32-bit architectures.

**Comment by japaric** [comment]
> each argument of that macro is passed through a register

On for that reason, the `syscall!` macro casts each argument to `usize` before using them in an [`asm!` block](https://github.com/japaric/syscall.rs/blob/master/src/platform/linux-x86/mod.rs#L55).

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 626a62f with merge 626a62f...

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 2f9d51c with merge 2f9d51c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193245040)
State: approved= try=True

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 8554c4c with merge 8554c4c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193314812)

**Comment by tbu-** [comment]
On `mips-unknown-linux-gnu`:

```
error[E0425]: cannot find function `syscall5` in module `sc`
   --> src/linux/mod.rs:130:9
    |
130 |         syscall!(PREAD64, fd, buffer, count, pos >> 32, pos & 0xffff_ffff) as ssize_t
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `sc::syscall0`?
    |
    = note: this error originates in a macro outside of the current crate

error[E0425]: cannot find function `syscall5` in module `sc`
   --> src/linux/mod.rs:167:9
    |
167 |         syscall!(PWRITE64, fd, buffer, count, pos >> 32, pos & 0xffff_ffff) as ssize_t
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `sc::syscall0`?
    |
    = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors

error: Could not compile `std`.

```

The `syscall` crate is missing `syscall5` on MIPS. The man page documents that the fifth argument is passed on the stack of the userspace program.

**Comment by tbu-** [comment]
On `armv7-unknown-linux-gnueabihf`, this gets called as
```
pwrite(3, "Hi?\n", 4, 820033810857984)  = -1 EFBIG (File too large)
```
Not yet investigated how that can happen.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit a15b86d with merge a15b86d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193374286)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3decf0c with merge 3decf0c...

**Comment by tbu-** [comment]
@japaric It should work now, but travis doesn't start testing it.

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193380852)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3decf0c has been approved by `japaric`

**Comment by japaric** [comment]
I'm not sure why homu is not working but merging manually since "try" passed.

**Pull request merged**
