### PR TITLE
ship custom targets

### LINKED ISSUE #53: Use custom targets
Given that we are forced to use `panic = abort`, which currently has to be specified in Cargo.toml, until we implement unwinding (#12) and that some crates may require modifications to be compiled against `steed` (e.g. use syscalls instead of the `libc` crate, or not use `last_os_error`), I propose that we create and ship with this repo custom targets that make it easier to deal with those two requirements.

In a nutshell, we would create custom targets named e.g. `x86_64-linux` that look very similar to their built-in counterparts, e.g. `x86_64-unknown-linux-gnu`, except for:

- Setting `panic-strategy` to `abort`

- Setting `env` to `steed` so people can use `cfg(target_env = "steed")` to make their crates compatible with `steed`

- And moving the linker flags that currently reside in [`.cargo/config`](https://github.com/japaric/steed/blob/master/.cargo/config) into the `pre-link-args` fields so people don't have to carry that file around to compile against `steed`.

The main downside is that to call `cargo build --target x86_64-linux` you would need to have the target specification file around. But I think that can be fixed by teaching `cross` how to support custom targets and by providing images that contain the target specification file and set `RUST_TARGET_PATH` as appropriate such that `cross build --target x86_64-linux` just works.

Thoughts on this?

### PR DESCRIPTION
**Pull request by japaric**
this simplifies usage

Users can now directly use `cross` to (cross) compile their crate
against `steed` without having to mess with `.cargo/config` or
`Cross.toml` or modify their `Cargo.toml`.

closes #53

cc @parched
this requires a new Cross release to land

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit b5d7715 with merge b5d7715...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/193774359)

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit c3a7493 with merge 65d3d1c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193923323)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a133291 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a133291 with merge 2524656...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194006363)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5389393 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5389393 with merge acc06ba...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194008568)
Approved by: japaric
Pushing acc06ba5adb45595bd6277bf18a8d2d69e6e116d to master...

**Pull request merged**
