### PR TITLE
retrieve the process stack pointer

### PR DESCRIPTION
**Pull request by japaric**
with this we'll be able to implement env::args, env::vars and getauxval

cc #7
cc #48

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 266bca5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 266bca5 with merge 6ce2131...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194022411)

**Comment by japaric** [comment]
I canceled the test to prioritize #66 

@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 266bca5 with merge 4dbd94a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194032244)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 266bca5 with merge e13d108...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194044398)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit efbe84f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit efbe84f with merge 6e0c5bf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194049594)
Approved by: japaric
Pushing 6e0c5bf32e2efb7c3065a62af120ad8b50804558 to master...

**Pull request merged**
