### PR TITLE
implement the `start` lang item

### LINKED ISSUE #14: Support normal `fn main()`
This should work:

``` rust
extern crate steed;

fn main() {
    println!("Hello, world!);
}
```

In theory, we only have to implement the `start` lang item then `fn main()` will just work. At the very least this going to require implementing env::args support (because of `start`'s signature) so ...

Blocked by #7

### PR DESCRIPTION
**Pull request by japaric**
with this one can use the normal form of `main` in executables, i.e. `fn
main() { .. }`

this commit also re-exports some macros from the `core` crate

closes #14

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5a443f7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5a443f7 with merge 5a443f7...

**Comment by tbu-** [comment]
\o/

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193233755)
Approved by: japaric
Pushing 5a443f7ccc94e00214aa6087c642b9a27bc97c00 to master...

**Comment by japaric** [comment]
I just realized that the `hello` example got very bloated recently:

```
$ size target/x86_64-unknown-linux-gnu/release/examples/hello
   text    data     bss     dec     hex filename
  26762    1216       0   27978    6d4a target/x86_64-unknown-linux-gnu/release/examples/hello
```

It was just 131 bytes of `.text` before, @tbu- do you know if an `unwrap` got introduced somewhere in `write_all`?

**Comment by japaric** [comment]
The good thing is that `zero` still optimizes very well even with the `start` abstraction introduced here:

```
$ objdump -Cd target/x86_64-unknown-linux-gnu/release/examples/zero

target/x86_64-unknown-linux-gnu/release/examples/zero:     file format elf64-x86-64


Disassembly of section .text:

00000000004000b0 <_start_rust>:
  4000b0:       31 ff                   xor    %edi,%edi
  4000b2:       b8 3c 00 00 00          mov    $0x3c,%eax
  4000b7:       0f 05                   syscall
  4000b9:       0f 1f 80 00 00 00 00    nopl   0x0(%rax)

00000000004000c0 <_start>:
  4000c0:       e8 eb ff ff ff          callq  4000b0 <_start_rust>

$ size target/x86_64-unknown-linux-gnu/release/examples/zero
   text    data     bss     dec     hex filename
     21       0       0      21      15 target/x86_64-unknown-linux-gnu/release/examples/zero
```

```
$ arm-none-eabi-objdump -Cd target/armv7-unknown-linux-gnueabihf/release/examples/zero

target/armv7-unknown-linux-gnueabihf/release/examples/zero:     file format elf32-littlearm


Disassembly of section .text:

00010094 <_start>:
   10094:       e92d4080        push    {r7, lr}
   10098:       e3a07001        mov     r7, #1
   1009c:       e3a00000        mov     r0, #0
   100a0:       ef000000        svc     0x00000000

$ arm-none-eabi-size target/armv7-unknown-linux-gnueabihf/release/examples/zero
   text    data     bss     dec     hex filename
     24       0       0      24      18 target/armv7-unknown-linux-gnueabihf/release/examples/zero
```

**Comment by tbu-** [comment]
The only idea I have is that it might be caused by the allocation of the trait object `Error` in `write_all`:
```
Ok(0) => return Err(Error::new(ErrorKind::WriteZero,
                               "failed to write whole buffer")),
```

**Comment by tbu-** [comment]
No, apparantly not that.

**Comment by japaric** [comment]
I think that's the cause. `hello` now contains the whole allocator in it. It's sad having to allocate to return an error 😢.

**Comment by tbu-** [comment]
Some experimenting tells me that once `write_all` becomes too large, the allocator is included. Probably because it no longer gets inlined and thus the code needs the `free` from the allocator (even if I remove all allocations there, you can replace the error creation by `Error::from(ErrorKind::WriteZero)` which doesn't allocate).

Can one somehow activate LTO to force the compiler to try inlining?

**Comment by tbu-** [comment]
(I.e. the allocation can be removed as shown above, but that doesn't make the binary significantly smaller, at least without further changes.)

**Comment by japaric** [comment]
> Can one somehow activate LTO to force the compiler to try inlining?

If you are compiling examples within this repo, LTO is already enabled. Adding some `#[inline]` here and there may help. You can also use `#[inline(always)]` if you are desperate. `#[inline]` only has effects on "conceret" functions; generic functions are implictly `#[inline]`.

**Pull request merged**
