### PR TITLE
Add more `io` stuff

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 395ac60 with merge 395ac60...

**Comment by tbu-** [comment]
The command "git checkout -qf 395ac602f4fb9acd3992253e1a7704cf098ba974" failed and exited with 128 during .

Doesn't look like this PR's fault.

**Comment by japaric** [comment]
> Doesn't look like this PR's fault.

That happens when you `try` two or more PRs at the same time. Homu should queue the `try` requests but instead it (force) pushes to the `try` branch and all but one PR breaks.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit ce7d2d9 with merge ce7d2d9...

**Comment by tbu-** [comment]
Apparantly you can't let @homunkulus retry without changing the commit.

**Comment by homunkulus** [comment]
:hourglass: Trying commit ce7d2d9 with merge ce7d2d9...

**Comment by tbu-** [comment]
Okay, with retry ._.

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/197837326)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-.

**Pull request merged**
