### PR TITLE
stabilize all the "steed" stuff

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 33cc81e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 33cc81e with merge 33cc81e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192000194)
Approved by: japaric
Pushing 33cc81e9520f94e1eeefef1f4467f65aa3d24184 to master...

**Pull request merged**
