### PR TITLE
`sys_common` is now closer to upstream

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 42b2928 with merge cc80f0a...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 42b2928 has been approved by `japaric`

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/199257046)
Approved by: japaric
Pushing cc80f0a3a09df75005e03ff226a3db5e4743a151 to master...

**Comment by homunkulus** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by tbu-** [comment]
I guess this just needs to be retried.

**Comment by japaric** [comment]
^ no-op commit to make homu pick this up again.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6dd2bca has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6dd2bca with merge c192fe7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/199352104)
Approved by: japaric
Pushing c192fe7ddac669112fb41502ba64f2a3ae62c5b4 to master...

**Pull request merged**
