### PR TITLE
Provide a `process` module that does nothing

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
I'll try to do #11 next.

@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e6a77f8 with merge e6a77f8...

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit f6ad289 with merge f6ad289...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/195730030)
State: approved= try=True

**Comment by japaric** [comment]
r=me, after a rebase

@homunkulus delegate+

(with that command, you should be able to r+ this PR, @tbu-)

**Comment by homunkulus** [comment]
:v: @tbu- can now approve this pull request

**Comment by tbu-** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 80de9a4 has been approved by `tbu-`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 80de9a4 with merge 80de9a4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/195798324)
Approved by: tbu-
Pushing 80de9a48f7c1b431915a6d27b7b73ef93c674035 to master...

**Pull request merged**
