### PR TITLE
ci: run ci/after_success.sh in the right phase

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b6409c9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b6409c9 with merge b6409c9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192000910)
Approved by: japaric
Pushing b6409c9748ce75591494930ddfc901a40deb225c to master...

**Pull request merged**
