### PR TITLE
implement env::args

### LINKED ISSUE #7: implement env::args
This is going to require messing with the stack in `_start` (the entry point). Whatever invokes the program, passes the program arguments through the stack and only `_start` can access them.

### PR DESCRIPTION
**Pull request by japaric**
closes #7
cc #69

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5729f13 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5729f13 with merge 5729f13...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194136047)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 9ab148c) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 4358fc7 with merge 4358fc7...

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 49bc81d with merge 49bc81d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/195669599)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #81) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e6dd58b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e6dd58b with merge e6dd58b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/198587314)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #102) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
Let's see what target breaks with this PR.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ab0858a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ab0858a with merge ab0858a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/221194571)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 93bd193 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 93bd193 with merge 93bd193...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/221196835)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f1624e5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f1624e5 with merge f1624e5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/221202138)
Approved by: japaric
Pushing f1624e5cf164554224430fca0d385e4667e17707 to master...

**Pull request merged**
