### PR TITLE
re-export the format! macro from the collections crate

### PR DESCRIPTION
**Pull request by japaric**
cc #23

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 123e23d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 123e23d with merge 123e23d...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 43d93a6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 43d93a6 with merge 43d93a6...

**Comment by japaric** [comment]
Merging manually since the test passed.

**Pull request merged**
