### PR TITLE
UPD -> UDP

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Doesn't really need tests, but, oh well. @homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 387345e with merge 387345e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/199168783)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-.

**Pull request merged**
