### PR TITLE
Add `File::seek`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
#70, #74 and #75 complete the `File` implementation (#18).

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit cb24865 with merge cb24865...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194198746)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit bd19d21 with merge bd19d21...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194201406)
State: approved= try=True

**Comment by japaric** [comment]
LGTM. r=me with a rebase

**Comment by tbu-** [comment]
@japaric Rebased.

**Comment by japaric** [comment]
Thanks, @tbu-.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9ab148c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9ab148c with merge 9ab148c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194264996)
Approved by: japaric
Pushing 9ab148c4820a5d2a21441769dd26ec912bd6237c to master...

**Pull request merged**
