### PR TITLE
"implement" std::collections

### PR DESCRIPTION
**Pull request by japaric**
the HashMap and HashSet has been commented out because they depend on
thread_local!

cc #5

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 92569cf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 92569cf with merge 92569cf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/191964469)
Approved by: japaric
Pushing 92569cfbe2fd72ead4c1a784e69ab2f30e258d8a to master...

**Pull request merged**
