### PR TITLE
always use the latest stable cross release

### LINKED ISSUE #152: Docker image got deleted
```
Unable to find image 'japaric/x86_64-unknown-linux-steed:v0.1.11' locally
Pulling repository docker.io/japaric/x86_64-unknown-linux-steed
docker: Tag v0.1.11 not found in repository docker.io/japaric/x86_64-unknown-linux-steed.
See 'docker run --help'.
```

Soo.. yeah. I'm not familiar with docker, seems like the documentation in the README is either out of date, the image got deleted or moved ...

### PR DESCRIPTION
**Pull request by japaric**
closes #152

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7439fc9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7439fc9 with merge 7439fc9...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/275605074?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a1aa573 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a1aa573 with merge a1aa573...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/275628943?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a1aa573a64c762d8e2a31b9bc8a5170957958d1d to master...

**Pull request merged**
