### PR TITLE
Port `src/sys/linux/fs.rs` to the new `libc`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
```diff
--- ../rust/src/libstd/sys/unix/fs.rs	2017-02-04 10:02:15.140676436 +0100
+++ src/sys/linux/fs.rs	2017-02-04 17:18:00.105215031 +0100
@@ -16,15 +16,13 @@
 use libc::{self, c_int, mode_t};
 use mem;
 use path::{Path, PathBuf};
-use ptr;
-use sync::Arc;
 use sys::fd::FileDesc;
 use sys::time::SystemTime;
 use sys::{cvt, cvt_r};
 use sys_common::{AsInner, FromInner};
 
 #[cfg(any(target_os = "linux", target_os = "emscripten"))]
-use libc::{stat64, fstat64, lstat64, off64_t, ftruncate64, lseek64, dirent64, readdir64_r, open64};
+use libc::{stat64, fstat64, lstat64, off64_t, ftruncate64, lseek64, open64};
 #[cfg(target_os = "android")]
 use libc::{stat as stat64, fstat as fstat64, lstat as lstat64, lseek64,
            dirent as dirent64, open as open64};
@@ -38,32 +36,53 @@
               target_os = "solaris")))]
 use libc::{readdir_r as readdir64_r};
 
+use linux;
+
 pub struct File(FileDesc);
 
-#[derive(Clone)]
-pub struct FileAttr {
-    stat: stat64,
-}
+pub struct ReadDir(Option<ReadDirInner>);
 
-pub struct ReadDir {
-    dirp: Dir,
-    root: Arc<PathBuf>,
+struct ReadDirInner {
+    fd: FileDesc,
+    root: PathBuf, // TODO: Replace by a `Arc<PathBuf>`
+    buf: Vec<u8>,
+    offset: usize,
+}
+
+impl ReadDir {
+    fn new(fd: FileDesc, root: PathBuf) -> ReadDir {
+        ReadDir(Some(ReadDirInner {
+            fd: fd,
+            root: root,
+            buf: Vec::with_capacity(32768),
+            offset: 0,
+        }))
+    }
 }
 
-struct Dir(*mut libc::DIR);
+pub struct DirEntry {
+    entry: linux::linux_dirent64,
+    name: OsString,
+    root: PathBuf,
+}
 
-unsafe impl Send for Dir {}
-unsafe impl Sync for Dir {}
+impl DirEntry {
+    pub unsafe fn from_raw(entry: *const linux::linux_dirent64,
+                           root: PathBuf)
+        -> DirEntry
+    {
+        let name = CStr::from_ptr((*entry).d_name.as_ptr()).to_bytes();
+        DirEntry {
+            entry: *entry,
+            name: OsStr::from_bytes(name).into(),
+            root: root,
+        }
+    }
+}
 
-pub struct DirEntry {
-    entry: dirent64,
-    root: Arc<PathBuf>,
-    // We need to store an owned copy of the directory name
-    // on Solaris because a) it uses a zero-length array to
-    // store the name, b) its lifetime between readdir calls
-    // is not guaranteed.
-    #[cfg(target_os = "solaris")]
-    name: Box<[u8]>
+#[derive(Clone)]
+pub struct FileAttr {
+    stat: stat64,
 }
 
 #[derive(Clone)]
@@ -195,77 +214,54 @@
 
 impl fmt::Debug for ReadDir {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        // This will only be called from std::fs::ReadDir, which will add a "ReadDir()" frame.
-        // Thus the result will be e g 'ReadDir("/home")'
-        fmt::Debug::fmt(&*self.root, f)
+        match self.0 {
+            Some(ref read_dir) => fmt::Debug::fmt(&read_dir.root, f),
+            None => fmt::Debug::fmt("<exhausted>", f),
+        }
     }
 }
 
 impl Iterator for ReadDir {
     type Item = io::Result<DirEntry>;
 
-    #[cfg(target_os = "solaris")]
     fn next(&mut self) -> Option<io::Result<DirEntry>> {
-        unsafe {
-            loop {
-                // Although readdir_r(3) would be a correct function to use here because
-                // of the thread safety, on Illumos the readdir(3C) function is safe to use
-                // in threaded applications and it is generally preferred over the
-                // readdir_r(3C) function.
-                super::os::set_errno(0);
-                let entry_ptr = libc::readdir(self.dirp.0);
-                if entry_ptr.is_null() {
-                    // NULL can mean either the end is reached or an error occurred.
-                    // So we had to clear errno beforehand to check for an error now.
-                    return match super::os::errno() {
-                        0 => None,
-                        e => Some(Err(Error::from_raw_os_error(e))),
+        let res;
+        'empty: loop {
+            let read_dir: &mut ReadDirInner = if let Some(ref mut d) = self.0 {
+                d
+            } else {
+                return None;
+            };
+            unsafe {
+                if read_dir.offset == read_dir.buf.len() {
+                    read_dir.offset = 0;
+                    read_dir.buf.clear();
+                    let read;
+                    match cvt(linux::getdents64(read_dir.fd.raw(),
+                                                read_dir.buf.as_mut_ptr() as *mut _,
+                                                read_dir.buf.capacity() as u32)) {
+                        Ok(n) => read = n as usize,
+                        Err(e) => {
+                            res = Some(Err(e));
+                            break 'empty;
+                        }
                     }
+                    if read == 0 {
+                        res = None;
+                        break 'empty;
+                    }
+                    assert!(read <= read_dir.buf.capacity());
+                    read_dir.buf.set_len(read);
                 }
+                let dent = &read_dir.buf[read_dir.offset]
+                    as *const u8 as *const linux::linux_dirent64;
+                read_dir.offset += (*dent).d_reclen as usize;
 
-                let name = (*entry_ptr).d_name.as_ptr();
-                let namelen = libc::strlen(name) as usize;
-
-                let ret = DirEntry {
-                    entry: *entry_ptr,
-                    name: ::slice::from_raw_parts(name as *const u8,
-                                                  namelen as usize).to_owned().into_boxed_slice(),
-                    root: self.root.clone()
-                };
-                if ret.name_bytes() != b"." && ret.name_bytes() != b".." {
-                    return Some(Ok(ret))
-                }
-            }
-        }
-    }
-
-    #[cfg(not(target_os = "solaris"))]
-    fn next(&mut self) -> Option<io::Result<DirEntry>> {
-        unsafe {
-            let mut ret = DirEntry {
-                entry: mem::zeroed(),
-                root: self.root.clone()
-            };
-            let mut entry_ptr = ptr::null_mut();
-            loop {
-                if readdir64_r(self.dirp.0, &mut ret.entry, &mut entry_ptr) != 0 {
-                    return Some(Err(Error::last_os_error()))
-                }
-                if entry_ptr.is_null() {
-                    return None
-                }
-                if ret.name_bytes() != b"." && ret.name_bytes() != b".." {
-                    return Some(Ok(ret))
-                }
+                return Some(Ok(DirEntry::from_raw(dent, read_dir.root.clone())));
             }
         }
-    }
-}
-
-impl Drop for Dir {
-    fn drop(&mut self) {
-        let r = unsafe { libc::closedir(self.0) };
-        debug_assert_eq!(r, 0);
+        self.0 = None;
+        res
     }
 }
 
@@ -346,9 +342,7 @@
               target_os = "haiku",
               target_os = "fuchsia"))]
     fn name_bytes(&self) -> &[u8] {
-        unsafe {
-            CStr::from_ptr(self.entry.d_name.as_ptr()).to_bytes()
-        }
+        self.name.as_bytes()
     }
     #[cfg(target_os = "solaris")]
     fn name_bytes(&self) -> &[u8] {
@@ -439,7 +433,7 @@
         //
         // The CLOEXEC flag, however, is supported on versions of OSX/BSD/etc
         // that we support, so we only do this on Linux currently.
-        if cfg!(target_os = "linux") {
+        if cfg!(target_os = "linux") && (flags & libc::O_PATH) != libc::O_PATH {
             fd.set_cloexec()?;
         }
 
@@ -594,7 +588,7 @@
 
         #[cfg(any(target_os = "linux", target_os = "macos"))]
         fn get_mode(fd: c_int) -> Option<(bool, bool)> {
-            let mode = unsafe { libc::fcntl(fd, libc::F_GETFL) };
+            let mode = unsafe { libc::fcntl(fd, libc::F_GETFL, 0) };
             if mode == -1 {
                 return None;
             }
@@ -626,16 +620,10 @@
 }
 
 pub fn readdir(p: &Path) -> io::Result<ReadDir> {
-    let root = Arc::new(p.to_path_buf());
-    let p = cstr(p)?;
-    unsafe {
-        let ptr = libc::opendir(p.as_ptr());
-        if ptr.is_null() {
-            Err(Error::last_os_error())
-        } else {
-            Ok(ReadDir { dirp: Dir(ptr), root: root })
-        }
-    }
+    let mut oo = OpenOptions::new();
+    oo.read(true);
+    oo.custom_flags(libc::O_DIRECTORY);
+    Ok(ReadDir::new(File::open(p, &oo)?.into_fd(), p.into()))
 }
 
 pub fn unlink(p: &Path) -> io::Result<()> {
@@ -743,17 +731,25 @@
 }
 
 pub fn canonicalize(p: &Path) -> io::Result<PathBuf> {
-    let path = CString::new(p.as_os_str().as_bytes())?;
-    let buf;
-    unsafe {
-        let r = libc::realpath(path.as_ptr(), ptr::null_mut());
-        if r.is_null() {
-            return Err(io::Error::last_os_error())
-        }
-        buf = CStr::from_ptr(r).to_bytes().to_vec();
-        libc::free(r as *mut _);
+    // Adapted from musl 1.1.16.
+    let mut oo = OpenOptions::new();
+    oo.read(true); // Ignored if O_PATH is set.
+    oo.custom_flags(libc::O_PATH);
+
+    let file = File::open(p, &oo)?;
+    let fd_stat = file.file_attr()?;
+    let fd = file.into_fd();
+
+    let canonical = readlink(Path::new(&format!("/proc/self/fd/{}", fd.raw())))?;
+    let canonical_stat = stat(&canonical)?;
+
+    if fd_stat.stat.st_dev != canonical_stat.stat.st_dev ||
+        fd_stat.stat.st_ino != canonical_stat.stat.st_ino
+    {
+        return Err(io::Error::from_raw_os_error(libc::ELOOP));
     }
-    Ok(PathBuf::from(OsString::from_vec(buf)))
+
+    Ok(canonical)
 }
 
 pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
```

The diff is larger because we implement our own `ReadDir` logic, implementing `libc`'s would be inefficient.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0fe14fb with merge c5b38bb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198654736)
State: approved= try=True

**Comment by japaric** [comment]
> +    root: PathBuf, // TODO: Replace by a `Arc<PathBuf>`

Why is `root` no wrapped in an `Arc` in the current implementation? Is it because we don't have threads yet? Seems better to use `Arc` now to not forget to add it later.

**Comment by tbu-** [comment]
@japaric I don't think we have `Arc` yet.

**Comment by FenrirWolf** [comment]
Would be pretty easy to pull in since it's just a libcollections reexport https://github.com/rust-lang/rust/blob/1.15.0/src/libstd/sync/mod.rs#L21

**Comment by japaric** [comment]
@tbu- r=me with the Arc change

@homunkulus delegate=tbu-

**Comment by homunkulus** [comment]
:v: @tbu- can now approve this pull request

**Comment by tbu-** [comment]
@homunkulus r=japaric

**Comment by homunkulus** [comment]
:pushpin: Commit a6c1d7c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a6c1d7c with merge 65c5230...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198909366)
Approved by: japaric
Pushing 65c5230c9400b018f08a7fadf989c2e8c7311744 to master...

**Pull request merged**
