### PR TITLE
Add `fs::Metadata`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
This is still missing support for a couple of architectures.

It seems that the syscall crate doesn't have `stat` or `lstat` for `aarch64`. Do you have an idea on how to replace these functions?

**Comment by japaric** [comment]
@tbu- MUSL uses FSTATAT where LSTAT is not available. Same thing with STAT.

**Comment by tbu-** [comment]
`FSTATAT` doesn't seem to be available either on `aarch64`. :/

```
$ grep STAT src/platform/linux-aarch64/nr.rs 
pub const FSTAT: usize = 80;
// pub const FSTAT64: usize = __NR_fstat64;
// pub const FSTATAT64: usize = __NR_fstatat64;
pub const FSTATFS: usize = 44;
// pub const FSTATFS64: usize = __NR_fstatfs64;
// pub const LSTAT: usize = __NR_lstat;
// pub const LSTAT64: usize = __NR_lstat64;
// pub const STAT: usize = __NR_stat;
// pub const STAT64: usize = __NR_stat64;
pub const STATFS: usize = 43;
// pub const STATFS64: usize = __NR_statfs64;
// pub const USTAT: usize = __NR_ustat;
```

Essentially only `FSTAT` available on `aarch64`... Maybe there's a bug in the tool that determines the syscalls?

**Comment by japaric** [comment]
> Maybe there's a bug in the tool that determines the syscalls?

The tool doesn't generate every single syscall out there; it just tries to determine the values for the syscalls in [this list](https://github.com/japaric/sc-gen/blob/master/src/main.rs#L60). Note that fstatat is not there.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0478f7a with merge 86f6c56...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194070754)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit bad33b6 with merge 84125d0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194077055)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bad33b6 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by homunkulus** [comment]
:pushpin: Commit bad33b6 has been approved by `japaric`

**Comment by japaric** [comment]
Homu got stuck ... Merging manually since try passed.

**Pull request merged**
