### PR TITLE
Activate some more tests

### LINKED ISSUE #116: implement TempDir (sys_common::io::test::TempDir)
this is used in some unit tests

### PR DESCRIPTION
**Pull request by tbu-**
Fixes #116.

### CODE REVIEW

**Comment by tbu-** [comment]
CC #115 

We do have `env::temp_dir`, but the environment map is not initialized for some reason, so it segfaults.

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1ef1adb with merge 1ef1adb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/224864180)
State: approved= try=True

**Comment by tbu-** [comment]
Oh, and this fixes #116.

**Comment by japaric** [comment]
Thanks, @tbu-!

**Pull request merged**
