### PR TITLE
Update the remaining parts to Rust 1.16.0

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Please merge this after #110 (it will conflict).

@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 61368b7 with merge 61368b7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/224523411)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 2b4aad6 with merge 2b4aad6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/224691716)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit aad7924 with merge f199f85...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/224696770)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-!

**Pull request merged**
