### PR TITLE
Fix errno constants on mips, mips64 and sparc

### LINKED ISSUE #54: errno constants are wrong on some architectures
Some constants, like `EBADFD`, have different values on different architectures:

```
$ rg 'define[ \t]*EBADFD'
include/uapi/asm-generic/errno.h
59:#define      EBADFD          77      /* File descriptor in bad state */

arch/sparc/include/uapi/asm/errno.h
68:#define      EBADFD          93      /* File descriptor in bad state */

arch/parisc/include/uapi/asm/errno.h
54:#define      EBADFD          168     /* File descriptor in bad state */

arch/mips/include/uapi/asm/errno.h
55:#define EBADFD               81      /* File descriptor in bad state */

arch/alpha/include/uapi/asm/errno.h
94:#define      EBADFD          114     /* File descriptor in bad state */
```

The implementation has to handle this using `cfg`s.

The architectures that usually use different values are SPARC and MIPS, which we are not currently considered supported platforms due to other bugs, so this is not a pressing issue. However, we'll have to fix this before listing those two architectures as supported.

cc @tbu-

### PR DESCRIPTION
**Pull request by tbu-**
Fixes #54.

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus test

**Comment by tbu-** [comment]
Merge after #102, didn't want to resolve merge conflicts.

**Comment by japaric** [comment]
Nice! Thanks, @tbu-. r=me after #102 lands.

@homunkulus delegate=tbu-

**Comment by homunkulus** [comment]
:v: @tbu- can now approve this pull request

**Comment by tbu-** [comment]
@homunkulus r=japaric

**Comment by homunkulus** [comment]
:pushpin: Commit 0d71621 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0d71621 with merge bdd48b3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198925724)
Approved by: japaric
Pushing bdd48b3334c90335498d45c46bdd0c4af5f091f9 to master...

**Pull request merged**
