### PR TITLE
move to Cross v0.1.9

### LINKED ISSUE #97: Allow offline compilation
I don't know what needs to be done to make that work, but I'd like to be able to compile without being connected to the internet.

```
$ cross run --target i686-unknown-linux-steed --example hashmap --no-default-features --features naive_ralloc
    Updating git repository `https://github.com/redox-os/ralloc`
warning: spurious network error (2 tries remaining): [12/-1] Failed to resolve address for github.com: Name or service not known
warning: spurious network error (1 tries remaining): [12/-1] Failed to resolve address for github.com: Name or service not known
error: failed to load source for a dependency on `ralloc`

Caused by:
  Unable to update https://github.com/redox-os/ralloc

Caused by:
  failed to fetch into /home/<user>/.cargo/git/db/ralloc-797ee1a3f928155b

To learn more, run the command again with --verbose.
error: couldn't generate Cargo.lock
caused by: `"cargo" "generate-lockfile" "--manifest-path" "/path/to/steed/Cargo.toml"` failed with exit code: Some(101)
note: run with `RUST_BACKTRACE=1` for a backtrace
```

### PR DESCRIPTION
**Pull request by japaric**
closes #97

waiting for a new binary release of Cross

cc @tbu-

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 843e48e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 843e48e with merge 843e48e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/199510321)
Approved by: japaric
Pushing 843e48e80605e85f1cf971694f3ed25c4493b5c9 to master...

**Comment by tbu-** [comment]
Yay! Thanks :)

**Pull request merged**
