### PR TITLE
README: update usage instructions

### PR DESCRIPTION
**Pull request by japaric**
they now tell you how to compile a crate against `steed` without having
to modify it

cc @briansmith

### CODE REVIEW

**Comment by japaric** [comment]
Need to realease a new version of Xargo and Cross before merging this.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e63cb74 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e63cb74 with merge e63cb74...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/193379030)
Approved by: japaric
Pushing e63cb740a88aa0007dd019b7f04c47c490b9e43e to master...

**Pull request merged**
