### PR TITLE
implement {error,num,prelude} and time::Duration

### PR DESCRIPTION
**Pull request by japaric**
all copy pasted

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ef16779 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ef16779 with merge ef16779...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/191995676)
Approved by: japaric
Pushing ef16779783f8ab34d5bfc60e1c8c5c265b5a6273 to master...

**Pull request merged**
