### PR TITLE
use custom docker images for i686, x86_64 and armv7hf

### LINKED ISSUE #15: Linker errors
When building

- the `open` and `vec` examples for `armv7-unknown-linux-gnueabihf`
- the `vec` example for `i686-unknown-linux-gnu` and `x86_64-unknown-linux-gnu`

in **release** mode. Note that LTO is enabled. This is the linker error:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/xargo/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/target/x86_64-unknown-linux-gnu/release/examples/vec-f6b3b7cebebee883.0.o" "-o" "/target/x86_64-unknown-linux-gnu/release/examples/vec-f6b3b7cebebee883" "-Wl,--gc-sections" "-Wl,-O1" "-nodefaultlibs" "-L" "/target/x86_64-unknown-linux-gnu/release/deps" "-L" "/target/release/deps" "-L" "/xargo/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/tmp/rustc.KuuDEWQSJZ1f/libcompiler_builtins-11b9715dd721de11.rlib" "-Wl,--build-id=none" "-nostartfiles" "-static"
  = note: /usr/bin/ld: /target/x86_64-unknown-linux-gnu/release/examples/vec-f6b3b7cebebee883: hidden symbol `core::panicking::panic::h55044ef132086b67' isn't defined
          /usr/bin/ld: final link failed: Bad value
          collect2: ld returned 1 exit status


error: aborting due to previous error
```

It's also the case that these targets are using gcc-4.6.2 (because of the cross
environment) to link the executables so that may be the problem.

It should be noted that cross users haven't reported any trouble linking Rust
programs using that old gcc version until now.

Let's:

- check if the problem goes away by making the `panic_fmt` lang item public.

- check if this is a regression by using an older nightly. There was a relevant
  change in how rustc emits symbols (it's now more strict about what's public,
  etc.) in the last month so that could contribute to the problem.

- check if installing gcc-4.7 in the cross environment solves the problem. If it
  does, then let's send a PR to [japaric/cross].

[japaric/cross]: https://github.com/japaric/cross

### PR DESCRIPTION
**Pull request by japaric**
these ship with more recent linkers that solve the linker errors we have
been seeing

closes #15

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3c74fee has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3c74fee with merge 3c74fee...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192834212)
Approved by: japaric
Pushing 3c74fee6b9b353db8622aed4678d3f026cee4ddb to master...

**Pull request merged**
