### PR TITLE
implement time::Instant and time::SystemTime

### LINKED ISSUE #10: implement std::time (Duration, SystemTime, Instant)
This is mainly copy pasting code from rust-lang/rust but it's going to require declaring some `struct`s like `timeval` and using system calls.

### PR DESCRIPTION
**Pull request by japaric**
closes #10

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 156e6b7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 156e6b7 with merge 156e6b7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/192015165)

**Comment by japaric** [comment]
> error: couldn't allocate output register for constraint '{r0}'

Yay, a typo in the sc crate. It has been fixed now.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f9cc200 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f9cc200 with merge f9cc200...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/192025955)
Approved by: japaric
Pushing f9cc200fd177329e4dd4dd4570b3aa04985defa0 to master...

**Pull request merged**
