### PR TITLE
ci: print the size of binaries

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5093ace has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5093ace with merge 5093ace...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/198226482)
Approved by: japaric
Pushing 5093ace43fbbd3d724907f31f37137379f63ed42 to master...

**Pull request merged**
