### PR TITLE
Add `fs::copy` and `fs::set_permissions`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 47c5896 with merge 6477f15...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/steed/builds/194604907)

**Comment by tbu-** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 731ff20 with merge e7c241e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/194609809)
State: approved= try=True

**Comment by japaric** [comment]
Thanks, @tbu-.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 731ff20 has been approved by `japaric`

**Comment by japaric** [comment]
(argh, homu!)

Merging manually.

**Pull request merged**
